name: "Create 'preview' release"

on:
  push:
    branches:
      - master

jobs:
  create_release:
    name: Create preview release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ITCHY_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Update 'preview' release
        run: |
          # First delete release + tag, ignore failures
          gh release delete preview || true
          sleep 5
          gh api -X DELETE /repos/{owner}/{repo}/git/refs/tags/preview || true
          sleep 5
          gh release create preview --prerelease --title preview
